export const REQUEST_TOKENS_PENDING = 'REQUEST_TOKENSPENDING';
export const REQUEST_TOKENS_SUCCESS = 'REQUEST_TOKENS_SUCCESS';
export const REQUEST_TOKENS_FAILED = 'REQUEST_TOKENS_FAILED';
export const REQUEST_ADD_FAV = 'REQUEST_ADD_FAV';
export const REQUEST_REMOVE_FAV = 'REQUEST_REMOVE_FAV';